FROM jenkins/jenkins:lts

# Apps
# if we want to install via apt - use root
# USER root
# RUN apt-get update && apt-get install -y
# drop back to the regular jenkins user - good practice
# USER jenkins

# Plugins
# COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
# RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

# Logging
# --env JAVA_OPTS="-Djava.util.logging.config.file=/var/jenkins_home/log.properties"
# COPY log.properties /var/jenkins_home/log.properties

